# Name of website
title: Michael Papageorgiou | Business Analytics

# Your name to show in the footer
author: Michael Papageorgiou
description: "Showcasing my coursework, skills, and expertise in data analytics."

# Navigation bar links
navbar-links:
  About Me: "#about"
  Coursework: "#coursework"
  CV: "#cv"
  Skills: "#skills"
  Languages: "#languages"

# Social media links
social-network-links:
  email: "mikepapageorgiou13@gmail.com"
  github: MichaelPap13
  linkedin: michael-papageorgiou
rss: false

# Theme colors
navbar-col: "#1f2937"  # dark gray
navbar-text-col: "#ffffff"  # white text
footer-col: "#1f2937"  # dark gray
footer-text-col: "#ffffff"  # white text
page-col: "#ffffff"  # white background
text-col: "#1f2937"  # dark gray text
link-col: "#0d6efd"  # blue links
hover-col: "#0b5ed7"  # darker blue hover

